# Generated by Django 2.2 on 2019-04-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0004_auto_20190428_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
