# Generated by Django 2.2 on 2019-04-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='article',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Article'),
        ),
    ]
